config/routes.rb
Rails.application.routes.draw do

  #mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    #get 'forget', to: 'users/passwords#forget'
    #patch 'update_password', to: 'users/passwords#update_password'
    #post '/login_validate', to: 'users/sessions#user_validate'
    #
    #unauthenticated :user do
    #  root to: "devise/sessions#new",as: :unauthenticated_root #设定登录页为系统默认首页
    #end
    #authenticated :user do
    #  root to: "homes#index",as: :authenticated_root #设定系统登录后首页
    #end
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'


  resources :properties do
  end
  resources :nests do
  end
  resources :domains do
  end

  resources :controls, :only => [:index]
  resources :templates do
    get :produce, :on => :member
  end

  resources :nlps do
    collection do
      post 'analyze'
    end
  end

  resources :notices
  resources :articles do
    get :export, :on => :collection
    get :main_image, :on => :member
    get :detail_image, :on => :member
  end

  resources :ocrs do
    post :analyze, :on => :collection
  end



  resources :statistics do
    get :line, :on => :member
    get :series, :on => :member
    get :column, :on => :member
    get :pie, :on => :member
    get :bar, :on => :member
    get :area, :on => :member
    get :scatter, :on => :member
  end

  resources :systems, :only => [] do
    get :send_confirm_code, :on => :collection
  end

  resources :users, :only => []  do
    get :center, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
    get :mobile_authc_new, :on => :member
    post :mobile_authc_create, :on => :member
    get :mobile_authc_status, :on => :member
  end

  resources :orders, :only => [:new, :create] do
    get :pay, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
  end

  resources :tasks, :only => [] do
    get :invite, :on => :collection
  end

  resources :accounts, :only => [:edit, :update] do
    get :recharge, :on => :collection 
    get :info, :on => :collection
    get :status, :on => :collection
  end

  resources :roles

  resources :spiders do
    get :start, :on => :member
  end
  resources :selectors

  resources :ctg_mtrls, :only => [] do
    get :list, :on => :collection
    get :ctg_xls_download, :on => :collection
    post :parse_excel, :on => :collection
  end
  resources :ctg_frsts do
    resources :ctg_secds do
      resources :ctg_mtrls do
      end
    end
  end

  resources :input_items, :only => [] do
    get :category, :on => :collection
    get :ware_item, :on => :collection
  end
  resources :ware_houses do
    get :completed, :on => :member
    get :canceled, :on => :member
    resources :input_items do
      get :current_ctg_mtrl, :on => :collection
      get :select_ctg_mtrl, :on => :collection
      get :input_item_create, :on => :collection
    end
  end
  resources :stocks do
    get :download_append, :on => :member
  end
  resources :retrievals do
    get :completed, :on => :member
    get :canceled, :on => :member
    get :download_append, :on => :member
    resources :output_items do
      get :current_stock, :on => :collection
      get :select_stock, :on => :collection
      get :output_item_create, :on => :collection
    end
  end
  resources :projects do
    get :outbound, :on => :member
    resources :picks do
      get :completed, :on => :member
      get :canceled, :on => :member
      resources :pick_items do
        get :current_stock, :on => :collection
        get :select_stock, :on => :collection
        get :pick_item_create, :on => :collection
      end
    end
  end
  resources :flower

  root :to => 'controls#index'
end

app/models/ctg_mtrl.rb
class CtgMtrl < ActiveRecord::Base
  #searchkick

  has_many :stocks, :dependent => :destroy
  accepts_nested_attributes_for :stocks, reject_if: :all_blank, allow_destroy: true

  has_many :input_items, :dependent => :destroy
  accepts_nested_attributes_for :input_items, reject_if: :all_blank, allow_destroy: true

  has_many :output_items, :dependent => :destroy
  accepts_nested_attributes_for :output_items, reject_if: :all_blank, allow_destroy: true

  has_many :enclosures, :dependent => :destroy
  accepts_nested_attributes_for :enclosures, reject_if: :all_blank, allow_destroy: true

  belongs_to :ctg_secd

  #after_commit :reindex_input_items

  #def reindex_input_items
  #  input_items.each do |input_item|
  #    input_item.reindex
  #  end
  #end

end


# == Schema Information
#
# Table name: ctg_mtrls
#
#  id          :integer         not null, primary key
#  idno        :string          default(""), not null
#  name        :string          default(""), not null
#  pet_name    :string          default(""), not null
#  model_no    :string          default(""), not null
#  unit        :string          default(""), not null
#  ctg_secd_id :integer
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

app/controllers/ctg_mtrls_controller.rb
class CtgMtrlsController < ApplicationController
  layout "application_control"
  before_filter :authenticate_user!
  #load_and_authorize_resource
  #
  def list
    ctg_frsts = current_user.ctg_frsts
    @ctg_frst = ctg_frsts.first
    unless @ctg_frst.nil?
      @ctg_secd = @ctg_frst.ctg_secds.first 
      unless @ctg_secd.nil?
        redirect_to ctg_frst_ctg_secd_ctg_mtrls_path(@ctg_frst, @ctg_secd)
      end
    end
  end

  def index 
    gon.ctg_nodes = []
    ctg_frsts = current_user.ctg_frsts
    prepare_nodes(ctg_frsts, gon.ctg_nodes)

    @ctg_frst = ctg_frsts.find(params[:ctg_frst_id])
    if @ctg_frst
      @ctg_secd = @ctg_frst.ctg_secds.find(params[:ctg_secd_id])
      if @ctg_secd
        @ctg_mtrls = @ctg_secd.ctg_mtrls.all
      end
    end
  end

  def ctg_xls_download
    send_file File.join(Rails.root, "public", "templates", "物品类目表.xlsx"), :filename => "物品类目表.xlsx", :type => "application/force-download", :x_sendfile=>true
  end
  

  def parse_excel
    excel = params["excel_file"]
    tool = ExcelTool.new
    results = tool.parseExcel(excel.path)

    first_name = ""
    second_name = ""
    idno = "" 
    mtrl_name = ""
    pet_name = ""
    model_no = ""
    unit = ""
    @frst_cache = nil 
    @secd_cache = nil 

    results["Sheet1"][1..-1].each do |items|
      items.each do |k, v|
        if !(/A/ =~ k).nil?
          first_name = v.nil? ? "" : v 
        elsif !(/B/ =~ k).nil?
          second_name = v.nil? ? "" : v 
        elsif !(/C/ =~ k).nil?
          idno = v.nil? ? "" : v 
        elsif !(/D/ =~ k).nil?
          mtrl_name = v.nil? ? "" : v 
        elsif !(/E/ =~ k).nil?
          pet_name = v.nil? ? "" : v 
        elsif !(/F/ =~ k).nil?
          model_no = v.nil? ? "" : v 
        elsif !(/G/ =~ k).nil?
          unit = v.nil? ? "" : v 
          break
        end
      end

      next if first_name.blank?

      if @frst_cache && @frst_cache.name == first_name
        @ctg_first = @frst_cache
      else
        ctg_firsts = CtgFrst.where(:name => first_name, :user_id => current_user.id)
        if ctg_firsts.blank?
          @ctg_first = CtgFrst.create!(:name => first_name, :user => current_user)
        else
          @ctg_first = ctg_firsts.first
        end
        @frst_cache = @ctg_first
      end

      if @secd_cache && @secd_cache.name == second_name
        @ctg_secd = @secd_cache
      else
        ctg_secds = CtgSecd.where(:name => second_name, :ctg_frst_id => @ctg_first.id)
        if ctg_secds.blank?
          @ctg_secd = CtgSecd.create!(:name => second_name, :ctg_frst_id => @ctg_first.id)
        else
          @ctg_secd = ctg_secds.first
        end
        @secd_cache = @ctg_secd
      end

      ctg_mtrls = CtgMtrl.where(:name => mtrl_name, :idno => idno, :pet_name => pet_name, :model_no => model_no, :unit => unit, :ctg_secd_id => @ctg_secd.id)

      if ctg_mtrls.blank?
        CtgMtrl.create!(:name => mtrl_name, :idno => idno, :pet_name => pet_name, :model_no => model_no, :unit => unit, :ctg_secd_id => @ctg_secd.id)
      end

    end
    redirect_to list_ctg_mtrls_path 
  end 

  def show
    ctg_frsts = current_user.ctg_frsts
    @ctg_frst = ctg_frsts.find(params[:ctg_frst_id])
    @ctg_secd = @ctg_frst.ctg_secds.find(params[:ctg_secd_id])
    @ctg_mtrl = @ctg_secd.ctg_mtrls.find(params[:id])
  end
   

   
  def new
    ctg_frsts = current_user.ctg_frsts
    @ctg_frst = ctg_frsts.find(params[:ctg_frst_id])
    @ctg_secd = @ctg_frst.ctg_secds.find(params[:ctg_secd_id])
    @ctg_mtrl = CtgMtrl.new
  end
   
  def create
    ctg_frsts = current_user.ctg_frsts
    @ctg_frst = ctg_frsts.find(params[:ctg_frst_id])
    @ctg_secd = @ctg_frst.ctg_secds.find(params[:ctg_secd_id])
    @ctg_mtrl = CtgMtrl.new(ctg_mtrl_params)
    @ctg_mtrl.ctg_secd = @ctg_secd
    if @ctg_mtrl.save
      redirect_to ctg_frst_ctg_secd_ctg_mtrls_path(@ctg_frst, @ctg_secd, @ctg_mtrl)
    else
      render :new
    end
  end
   

   
  def edit
    ctg_frsts = current_user.ctg_frsts
    @ctg_frst = ctg_frsts.find(params[:ctg_frst_id])
    @ctg_secd = @ctg_frst.ctg_secds.find(params[:ctg_secd_id])
    @ctg_mtrl = @ctg_secd.ctg_mtrls.find(params[:id])
  end
   

   
  def update
    ctg_frsts = current_user.ctg_frsts
    @ctg_frst = ctg_frsts.find(params[:ctg_frst_id])
    @ctg_secd = @ctg_frst.ctg_secds.find(params[:ctg_secd_id])
    @ctg_mtrl = @ctg_secd.ctg_mtrls.find(params[:id])
    if @ctg_mtrl.update(ctg_mtrl_params)
      redirect_to ctg_frst_ctg_secd_ctg_mtrls_path(@ctg_frst, @ctg_secd, @ctg_mtrl)
    else
      render :edit
    end
  end
   
  #def destroy
  #  ctg_frsts = current_user.ctg_frsts
  #  @ctg_frst = ctg_frsts.find(params[:ctg_frst_id])
  #  @ctg_secd = @ctg_frst.ctg_secds.find(params[:ctg_secd_id])
  #  @ctg_mtrl = @ctg_secd.ctg_mtrls.find(params[:id])
  #  @ctg_mtrl.destroy
  #  redirect_to :action => :index
  #end
   
  private
    def ctg_mtrl_params
      params.require(:ctg_mtrl).permit( :idno, :name, :pet_name, :model_no , enclosures_attributes: enclosure_params)
    end
  
    def enclosure_params
      [:id, :file, :_destroy]
    end
  
    def prepare_nodes(ctg_frsts, nodes)
      ctg_frsts.each do |frst|
        frst_h = Hash.new
        frst_h['name'] = frst.name
        frst_h['drag'] = false 
        frst_h['open'] = false 

        secd_arr = []
        ctg_secds = frst.ctg_secds
        ctg_secds.each do |secd|
          secd_h = Hash.new
          secd_h['name'] = secd.name
          secd_h['drag'] = false 
          secd_h['open'] = false 
          secd_h['target'] = "_self"
          secd_h['url'] = ctg_frst_ctg_secd_ctg_mtrls_path(frst.id, secd.id)  
          secd_arr << secd_h 
        end
        frst_h['children'] = secd_arr
        nodes << frst_h 
      end
    end
   
  
  
end

app/helpers/ctg_mtrls_helper.rb
module CtgMtrlsHelper

  #def options_for_ctg(my_secd)
  #  ctg_frsts = current_user.ctg_frsts
  #  str = ""
  #  ctg_frsts.each do |frst|
  #    str += " <optgroup label='#{frst.name}'>"
  #    ctg_secds = frst.ctg_secds
  #    ctg_secds.each do |secd|
  #      if !secd.nil? && secd.id == my_secd.id
  #        str += " <option selected='selected' value='#{secd.id}'>#{secd.name}</option>"
  #      else
  #        str += " <option value='#{secd.id}'>#{secd.name}</option>"
  #      end
  #    end
  #    str += "</optgroup>"
  #  end
  #  raw(str)
  #end                                            

  def options_for_domain_level(level) 
    levels = [Setting.domains.level_one, Setting.domains.level_two, Setting.domains.level_three]

    str = "<option value='0'>无</option>"
    if !level.nil? && levels.include?(level) 
      str += "<option selected='selected' value='" + level + "'>" + level + "</option>"
    end
    ls = levels.reject do |l|
      l == level
    end
    ls.each do |item|
        str += "<option value='" + item + "'>" + item + "</option>"
    end
    raw(str)
  end
end  

app/views/ctg_mtrls/_enclosure_fields.html.haml
.nested-fields.col-2.nestd-item
  .form-group
    .field.d-inline
      %label.newbtn
        = image_tag f.enclosure_image, :class => "blah"
        = f.file_field :file, :accept => "image/png, image/jpeg, image/gif", :class => "select-file", :onchange => "readURL(this);"
    = link_to_remove_association "X", f, :class => "nestd-notify-badge"

app/views/ctg_mtrls/_form.html.haml
.container-fluid
  .row.justify-content-sm-center
    .col-sm-12
      = form_for [@ctg_frst, @ctg_secd, @ctg_mtrl], :builder => WebsiteFormBuilder, :html => {:'data-parsley-validate' => true} do |f|
        - if @ctg_mtrl.errors.any?
          #error_explanation.alert.alert-danger.alert-dismissible.fade.show
            %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
              %span{"aria-hidden" => "true"} x 
            %h2= "#{pluralize(@ctg_mtrl.errors.count, "error")} prohibited this buyer from being saved:"
            %ul
              - @ctg_mtrl.errors.full_messages.each do |msg|
                %li= msg
      
        -#
          .form-group.row
            = f.label '所属类目', :class => "col-sm-3 col-form-label text-right"
            .col-sm-6
              = select_tag "ctg_secd", options_for_ctg(@ctg_mtrl.ctg_secd), :class=>"form-control", :required => true

        .form-group.row
          = f.label Setting.ctg_mtrls.idno, :class => "col-sm-3 col-form-label text-right"
          .col-sm-6
            = f.text_field :idno, :class => "form-control rounded-0" , :required => true
          
        .form-group.row
          = f.label Setting.ctg_mtrls.name, :class => "col-sm-3 col-form-label text-right"
          .col-sm-6
            = f.text_field :name, :class => "form-control rounded-0" , :required => true
          
        .form-group.row
          = f.label Setting.ctg_mtrls.pet_name, :class => "col-sm-3 col-form-label text-right"
          .col-sm-6
            = f.text_field :pet_name, :class => "form-control rounded-0" 
          
        .form-group.row
          = f.label Setting.ctg_mtrls.model_no, :class => "col-sm-3 col-form-label text-right"
          .col-sm-6
            = f.text_field :model_no, :class => "form-control rounded-0" 
          
      
      
      
        .form-group.row
          = f.label "附图", :class => "col-3 text-right col-form-label col-form-label"
          .col-9
            .row
              = f.fields_for :enclosures do |enclosure|
                = render 'enclosure_fields', f: enclosure
              .links
                = link_to_add_association "添加文件", f, :enclosures, :class => "button button-primary"
      
      
      
        .form-group.row
          .col-3.offset-3
            = f.submit '保存', :class => "button button-action"
        -#
          .col-3.offset-1
            = link_to '返回', ctg_mtrls_path, :class => "button button-caution"

app/views/ctg_mtrls/edit.html.haml
- provide(:title, t('.title'))

.container-fluid
  .row
    = render "layouts/control_sidebar"
    %main.col-md-9.ml-sm-auto.col-lg-10.p-3{:role => "main"}
      - content_for :card_header do
        %h5
          = fa_icon "wpforms", text: t(controller_name + "." + action_name + '.title')
          = link_to "/ctg_frsts/#{@ctg_frst.id}/ctg_secds/#{@ctg_secd.id}/ctg_mtrls", :class => "button button-small pull-right button-primary" do
            = fa_icon " chevron-left", text: Setting.systems.btn_back, right: false 

      - content_for :card_body do
        .container-fluid.p-0
          .row
            .col-md-12
              .card-body
                = render 'form'

      = render "layouts/bootstrap/card"

app/views/ctg_mtrls/index.html.haml
- provide(:title, t('.title'))


.container-fluid
  .row
    = render "layouts/control_sidebar"
    %main.col-md-9.ml-sm-auto.col-lg-10.p-3{:role => "main"}
      - content_for :card_header do
        %h5
          = fa_icon "list", text: @ctg_frst.name + "/" + @ctg_secd.name 
          = link_to ctg_xls_download_ctg_mtrls_path, :class => "button button-royal pull-right button-small mr-1" do
            下载名录表模板
          %button.button.button-caution.button-small.pull-right.mr-1{"data-target" => "#exampleModal", "data-toggle" => "modal", :type => "button"}
            上传名录表

          = link_to ctg_frsts_path, :class => "button button-small pull-right button-action mr-1" do  
            = fa_icon "sitemap", text: "类目管理", right: false 

          = link_to "/ctg_frsts/#{@ctg_frst.id}/ctg_secds/#{@ctg_secd.id}/#{controller_name}/new", :class => "button button-small pull-right button-primary mr-1" do
            = fa_icon "plus", text: Setting.systems.btn_new, right: false 
      - content_for :card_body do
        .container-fluid
          .row
            .col-sm-2.ctg-tree-ctn.border-right
              %ul#ctg-tree.ztree
            .col-sm-10
              %table.text-center.table-sm{:'data-toggle' => "table", :"data-pagination"=>"true", :'data-id-table'=>"advancedTable", :'data-search' => 'true'}
                %thead
                  %tr
                    %th{:scope => "col"} #
                  
                    %th{:scope => "col"}
                      = Setting.ctg_mtrls.idno
                    %th{:scope => "col"}
                      = Setting.ctg_mtrls.name
                    %th{:scope => "col"}
                      = Setting.ctg_mtrls.model_no
                    %th{:scope => "col"}
                      = Setting.ctg_mtrls.unit
                    %th{:scope => "col"}
                      = Setting.ctg_mtrls.pet_name
                    %th{:scope => "col"}
                      设置
                %tbody
                  - @ctg_mtrls.each_with_index do |ctg_mtrl, index|
                    %tr
                      %td{:scope => "row"}
                        = index+1
                    
                      %td
                        = ctg_mtrl.idno
                      %td
                        = ctg_mtrl.name
                      %td
                        = ctg_mtrl.model_no
                      %td
                        = ctg_mtrl.unit
                      %td
                        = ctg_mtrl.pet_name
                      %td
                        .container-fluid
                          .row.justify-content-center
                            = link_to "编辑", edit_ctg_frst_ctg_secd_ctg_mtrl_path(ctg_mtrl.ctg_secd.ctg_frst, ctg_mtrl.ctg_secd, ctg_mtrl), :class => "button button-highlight button-small mr-1" 
                            -#
                              = link_to "详细",  ctg_frst_ctg_secd_ctg_mtrl_path(ctg_mtrl.ctg_secd.ctg_frst, ctg_mtrl.ctg_secd, ctg_mtrl), :class => "button button-primary button-small mr-1" 
                              = link_to "删除", ctg_frst_ctg_secd_ctg_mtrl_path(ctg_mtrl.ctg_secd.ctg_frst, ctg_mtrl.ctg_secd, ctg_mtrl), :method => :delete, :data => {:confirm => "确定删除吗?"}, :class => "button button-caution button-small" 
      = render "layouts/bootstrap/card"

#exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title 物品名录表上传 
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} x 
      .modal-body
        = form_tag "/ctg_mtrls/parse_excel", multipart: true, id: "form-parse-excel" do
          .form-group.row
            = label_tag "物品名录表", nil, :class => "col-4 text-right col-form-label col-form-label"
            .col-8
              = file_field_tag "excel_file", :required => true 
          .form-group.row
            .col-sm-12
              .progress.ctn-progress
                .progress-bar.w-100.progress-bar-striped.progress-bar-animated{:role => "progressbar", :"aria-valuenow" => "100", :"aria-valuemin" => "0", :"aria-valuemax" => "100"}
          .form-group.row
            .col-8
              = submit_tag '保存', :class => "btn btn-primary btn-parse-submit " 

app/views/ctg_mtrls/list.html.haml
- provide(:title, t('.title'))


.container-fluid
  .row
    = render "layouts/control_sidebar"
    %main.col-md-9.ml-sm-auto.col-lg-10.p-3{:role => "main"}
      - content_for :card_header do
        %h5
          = link_to ctg_xls_download_ctg_mtrls_path, :class => "button button-royal pull-right button-small mr-1" do
            下载物品名录表模板
          %button.button.button-caution.button-small.pull-right.mr-1{"data-target" => "#exampleModal", "data-toggle" => "modal", :type => "button"}
            上传名录表
      - content_for :card_body do
        .container-fluid
          .row
            .col-sm-12
              %h2
                请先上传类目表，初始化物品名录
      = render "layouts/bootstrap/card"

#exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title 名录表上传 
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} x 
      .modal-body
        = form_tag "/ctg_mtrls/parse_excel", multipart: true, id: "form-parse-excel" do
          .form-group.row
            = label_tag "物品名录表", nil, :class => "col-4 text-right col-form-label col-form-label"
            .col-8
              = file_field_tag "excel_file", :required => true 
          .form-group.row
            .col-sm-12
              .progress.ctn-progress
                .progress-bar.w-100.progress-bar-striped.progress-bar-animated{:role => "progressbar", :"aria-valuenow" => "100", :"aria-valuemin" => "0", :"aria-valuemax" => "100"}
          .form-group.row
            .col-8
              = submit_tag '保存', :class => "btn btn-primary btn-parse-submit " 

app/views/ctg_mtrls/new.html.haml
- provide(:title, t('.title'))

.container-fluid
  .row
    = render "layouts/control_sidebar"
    %main.col-md-9.ml-sm-auto.col-lg-10.p-3{:role => "main"}
      - content_for :card_header do
        %h5
          = fa_icon "plus-square-o", text: t(controller_name + "." + action_name + '.title')
          = link_to "/ctg_frsts/#{@ctg_frst.id}/ctg_secds/#{@ctg_secd.id}/ctg_mtrls", :class => "button button-small pull-right button-primary" do
            = fa_icon " chevron-left", text: Setting.systems.btn_back, right: false 

      - content_for :card_body do
        .container-fluid.p-0
          .row
            .col-md-12
              .card-body
                = render 'form'

      = render "layouts/bootstrap/card"

app/views/ctg_mtrls/show.html.haml
- provide(:title, t('.title'))

.container-fluid
  .row
    = render "layouts/control_sidebar"
    %main.col-md-9.ml-sm-auto.col-lg-10.p-3{:role => "main"}
      - content_for :card_header do
        %h5
          = fa_icon "newspaper-o", text: t(controller_name + "." + action_name + '.title')
          = link_to "/#{controller_name}", :class => "button pull-right button-primary" do
            = fa_icon " chevron-left", text: Setting.systems.btn_back, right: false 
      - content_for :card_body do
        .container-fluid
          .row
            .col-md-8.offset-2
              .card-body
                .container-fluid
                  .row
                  
                    .col-md-6.mb-3.mr-3
                      = Setting.ctg_mtrls.idno
                      = @ctg_mtrl.idno
                  
                    .col-md-6.mb-3.mr-3
                      = Setting.ctg_mtrls.name
                      = @ctg_mtrl.name
                  
                    .col-md-6.mb-3.mr-3
                      = Setting.ctg_mtrls.pet_name
                      = @ctg_mtrl.pet_name
                  
                    .col-md-6.mb-3.mr-3
                      = Setting.ctg_mtrls.model_no
                      = @ctg_mtrl.model_no
                  
                  .row
                  
                  .row
                  
                    - @ctg_mtrl.enclosures.each do |e|
                      .col-md-6
                        = image_tag e.file_url(:small_width), :class => "w-100"
                  
                  .row
                  
                  
                  .row
                  
      = render "layouts/bootstrap/card"