config/routes.rb
Rails.application.routes.draw do

  #mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    #get 'forget', to: 'users/passwords#forget'
    #patch 'update_password', to: 'users/passwords#update_password'
    #post '/login_validate', to: 'users/sessions#user_validate'
    #
    #unauthenticated :user do
    #  root to: "devise/sessions#new",as: :unauthenticated_root #设定登录页为系统默认首页
    #end
    #authenticated :user do
    #  root to: "homes#index",as: :authenticated_root #设定系统登录后首页
    #end
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'


  resources :properties do
  end
  resources :nests do
  end
  resources :domains do
  end

  resources :controls, :only => [:index]
  resources :templates do
    get :produce, :on => :member
  end

  resources :nlps do
    collection do
      post 'analyze'
    end
  end

  resources :notices
  resources :articles do
    get :export, :on => :collection
    get :main_image, :on => :member
    get :detail_image, :on => :member
  end

  resources :ocrs do
    post :analyze, :on => :collection
  end



  resources :statistics do
    get :line, :on => :member
    get :series, :on => :member
    get :column, :on => :member
    get :pie, :on => :member
    get :bar, :on => :member
    get :area, :on => :member
    get :scatter, :on => :member
  end

  resources :systems, :only => [] do
    get :send_confirm_code, :on => :collection
  end

  resources :users, :only => []  do
    get :center, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
    get :mobile_authc_new, :on => :member
    post :mobile_authc_create, :on => :member
    get :mobile_authc_status, :on => :member
  end

  resources :orders, :only => [:new, :create] do
    get :pay, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
  end

  resources :tasks, :only => [] do
    get :invite, :on => :collection
  end

  resources :accounts, :only => [:edit, :update] do
    get :recharge, :on => :collection 
    get :info, :on => :collection
    get :status, :on => :collection
  end

  resources :roles

  resources :spiders do
    get :start, :on => :member
  end
  resources :selectors

  resources :ctg_mtrls, :only => [] do
    get :list, :on => :collection
    get :ctg_xls_download, :on => :collection
    post :parse_excel, :on => :collection
  end
  resources :ctg_frsts do
    resources :ctg_secds do
      resources :ctg_mtrls do
      end
    end
  end

  resources :input_items, :only => [] do
    get :category, :on => :collection
    get :ware_item, :on => :collection
  end
  resources :ware_houses do
    get :completed, :on => :member
    get :canceled, :on => :member
    resources :input_items do
      get :current_ctg_mtrl, :on => :collection
      get :select_ctg_mtrl, :on => :collection
      get :input_item_create, :on => :collection
    end
  end
  resources :stocks do
    get :download_append, :on => :member
  end
  resources :retrievals do
    get :completed, :on => :member
    get :canceled, :on => :member
    get :download_append, :on => :member
    resources :output_items do
      get :current_stock, :on => :collection
      get :select_stock, :on => :collection
      get :output_item_create, :on => :collection
    end
  end
  resources :projects do
    get :outbound, :on => :member
    resources :picks do
      get :completed, :on => :member
      get :canceled, :on => :member
      resources :pick_items do
        get :current_stock, :on => :collection
        get :select_stock, :on => :collection
        get :pick_item_create, :on => :collection
      end
    end
  end
  resources :flower

  root :to => 'controls#index'
end

app/models/notice.rb
class Notice < ActiveRecord::Base

  has_many :enclosures, :dependent => :destroy
  accepts_nested_attributes_for :enclosures, reject_if: :all_blank, allow_destroy: true


end


# == Schema Information
#
# Table name: notices
#
#  id         :integer         not null, primary key
#  title      :string          default(""), not null
#  content    :text
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  layout "application_control"
  before_filter :authenticate_user!
  #load_and_authorize_resource

   
  def index
    @notices = Notice.all
  end
   

   
  def show
    @notice = Notice.find(params[:id])
  end
   

   
  def new
    @notice = Notice.new
    
  end
   

   
  def create
    @notice = Notice.new(notice_params)
    #@notice.user = current_user
    if @notice.save
      redirect_to @notice
    else
      render :new
    end
  end
   

   
  def edit
    @notice = Notice.find(params[:id])
  end
   

   
  def update
    @notice = Notice.find(params[:id])
    if @notice.update(notice_params)
      redirect_to notice_path(@notice) 
    else
      render :edit
    end
  end
   

   
  def destroy
    @notice = Notice.find(params[:id])
    @notice.destroy
    redirect_to :action => :index
  end
   

  private
    def notice_params
      params.require(:notice).permit( :title, :content , enclosures_attributes: enclosure_params)
    end
  
    def enclosure_params
      [:id, :file, :_destroy]
    end
  
  
end

app/views/notices/_enclosure_fields.html.haml
.nested-fields
  .form-group
    .field.d-inline
      = f.file_field :file, :accept => "image/png, image/jpeg, image/gif", :class => "select-file"
    = link_to_remove_association "删除", f, :class => "btn btn-danger btn-sm d-inline"

app/views/notices/_form.html.haml
.container-fluid
  .row.justify-content-sm-center
    .col-sm-12
      = form_for @notice do |f|
        - if @notice.errors.any?
          #error_explanation
            %h2= "#{pluralize(@notice.errors.count, "error")} prohibited this buyer from being saved:"
            %ul
              - @notice.errors.full_messages.each do |msg|
                %li= msg
      
        .form-group.row
          = f.label Setting.notices.title, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :title, :class => "form-control"
          
        .form-group.row
          = f.label Setting.notices.content, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_area :content, :class => "form-control", :rows => "20"
          
      
        .form-group.row
          = f.label "主图", :class => "col-sm-1 control-label"
          .col-sm-11
            = f.fields_for :enclosures do |enclosure|
              = render 'enclosure_fields', f: enclosure
            .links
              = link_to_add_association "添加文件", f, :enclosures, :class => "btn btn-success"
      
      
        .form-group.row
          .col-sm-3.offset-sm-2
            = f.submit '保存', :class => "btn btn-success"
          .col-sm-3.offset-sm-1
            = link_to '返回', notices_path, :class => "btn btn-danger"

app/views/notices/edit.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  = render 'form'

= render "layouts/control_panel"

app/views/notices/index.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  .container-fluid.p-0
    .row
      .col-md-12
        %table.text-center.table-bordered.table-sm{:'data-toggle' => "table", :"data-pagination"=>"true", :"data-search" => "true",:'data-advanced-search'=>"true", :'data-id-table'=>"advancedTable"}
          %thead.thead-light
            %tr
              %th{:scope => "col"} #
            
              %th{:scope => "col"}
                = Setting.notices.title
              %th{:scope => "col"}
                = Setting.notices.content
              %th{:scope => "col"}
          %tbody
            - @notices.each_with_index do |notice, index|
              %tr
                %td{:scope => "row"}
                  = index+1
              
                %td
                  = notice.title
                %td
                  = notice.content
                %td
                  .container-fluid
                    .row
                      = link_to notice_path(notice), :class => "text-info col" do
                        = fa_icon "search"
                      = link_to edit_notice_path(notice), :class => "text-success col" do
                        = fa_icon "edit"
                      = link_to notice, :method => :delete, :data => {:confirm => "确定删除吗?"}, :class => "text-danger col" do
                        = fa_icon "trash"

= render "layouts/control_panel"

app/views/notices/new.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  = render 'form'

= render "layouts/control_panel"

app/views/notices/show.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  .container-fluid
    .row
      .col-md-12
        %table.table.text-center.table-bordered
          %thead
            %tr
            
              %th 
                = Setting.notices.title
              %th 
                = Setting.notices.content
          %tbody
            %tr
            
              %td
                = @notice.title
              %td
                = @notice.content
    
      .col-md-12
        - @notice.enclosures.each do |e|
          = image_tag e.file_url(:small_width)
    

= render "layouts/control_panel"