config/routes.rb
Rails.application.routes.draw do

  #mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    #get 'forget', to: 'users/passwords#forget'
    #patch 'update_password', to: 'users/passwords#update_password'
    #post '/login_validate', to: 'users/sessions#user_validate'
    #
    #unauthenticated :user do
    #  root to: "devise/sessions#new",as: :unauthenticated_root #设定登录页为系统默认首页
    #end
    #authenticated :user do
    #  root to: "homes#index",as: :authenticated_root #设定系统登录后首页
    #end
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'


  resources :properties do
  end
  resources :nests do
  end
  resources :domains do
  end

  resources :controls, :only => [:index]
  resources :templates do
    get :produce, :on => :member
  end

  resources :nlps do
    collection do
      post 'analyze'
    end
  end

  resources :notices
  resources :articles do
    get :export, :on => :collection
    get :main_image, :on => :member
    get :detail_image, :on => :member
  end

  resources :ocrs do
    post :analyze, :on => :collection
  end



  resources :statistics do
    get :line, :on => :member
    get :series, :on => :member
    get :column, :on => :member
    get :pie, :on => :member
    get :bar, :on => :member
    get :area, :on => :member
    get :scatter, :on => :member
  end

  resources :systems, :only => [] do
    get :send_confirm_code, :on => :collection
  end

  resources :users, :only => []  do
    get :center, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
    get :mobile_authc_new, :on => :member
    post :mobile_authc_create, :on => :member
    get :mobile_authc_status, :on => :member
  end

  resources :orders, :only => [:new, :create] do
    get :pay, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
  end

  resources :tasks, :only => [] do
    get :invite, :on => :collection
  end

  resources :accounts, :only => [:edit, :update] do
    get :recharge, :on => :collection 
    get :info, :on => :collection
    get :status, :on => :collection
  end

  resources :roles

  resources :spiders do
    get :start, :on => :member
  end
  resources :selectors

  resources :ctg_mtrls, :only => [] do
    get :list, :on => :collection
    get :ctg_xls_download, :on => :collection
    post :parse_excel, :on => :collection
  end
  resources :ctg_frsts do
    resources :ctg_secds do
      resources :ctg_mtrls do
      end
    end
  end

  resources :input_items, :only => [] do
    get :category, :on => :collection
    get :ware_item, :on => :collection
  end
  resources :ware_houses do
    get :completed, :on => :member
    get :canceled, :on => :member
    resources :input_items do
      get :current_ctg_mtrl, :on => :collection
      get :select_ctg_mtrl, :on => :collection
      get :input_item_create, :on => :collection
    end
  end
  resources :stocks do
    get :download_append, :on => :member
  end
  resources :retrievals do
    get :completed, :on => :member
    get :canceled, :on => :member
    get :download_append, :on => :member
    resources :output_items do
      get :current_stock, :on => :collection
      get :select_stock, :on => :collection
      get :output_item_create, :on => :collection
    end
  end
  resources :projects do
    get :outbound, :on => :member
    resources :picks do
      get :completed, :on => :member
      get :canceled, :on => :member
      resources :pick_items do
        get :current_stock, :on => :collection
        get :select_stock, :on => :collection
        get :pick_item_create, :on => :collection
      end
    end
  end
  resources :flower

  root :to => 'controls#index'
end

app/models/pick_item.rb
class PickItem < ActiveRecord::Base
  validates_numericality_of :count, :only_integer => true, :greater_than_or_equal_to => 0 

  belongs_to :pick


  belongs_to :stock

  def add_count(count)
    update_attributes!(:count => count)
  end

end

app/controllers/pick_items_controller.rb
class PickItemsController < ApplicationController
  layout "application_control"
  before_filter :authenticate_user!
  #load_and_authorize_resource

   
  def index
    @projects = current_user.projects
    @project = @projects.find(params[:project_id])
    @picks = @project.picks
    @pick = @picks.find(params[:pick_id])
    @pick.selecting
    @pick_items = @pick.pick_items
    gon.project = @project.id
    gon.pick = @pick.id
  end
   
  def current_stock
    @projects = current_user.projects
    @project = @projects.find(params[:project_id])
    @picks = @project.picks
    @pick = @picks.find(params[:pick_id])
    @pick_items = @pick.pick_items
    unless @pick_items.blank?
      mtrl_arr = []
      @pick_items.each do |pick_item|
        ctg_mtrl = pick_item.stock.ctg_mtrl
        mtrl_arr << ctg_mtrl.id
      end
      @stocks = current_user.stocks.where('ctg_mtrl_id not in (?)', mtrl_arr)
    else
      @stocks = current_user.stocks
    end
  end

  def select_stock
    @projects = current_user.projects
    @project = @projects.find(params[:project_id])
    @picks = @project.picks
    @pick = @picks.find(params[:pick_id])
    stock_ids = params[:selections].split(",")
    unless stock_ids.empty?
      @stocks = Stock.find(stock_ids)
      @stocks.each do |stock|
        PickItem.create(:pick => @pick, :stock => stock)
      end
    end
    redirect_to project_pick_pick_items_path(@project, @pick)
  end

  def pick_item_create
    @projects = current_user.projects
    @project = @projects.find(params[:project_id])
    @picks = @project.picks
    @pick = @picks.find(params[:pick_id])
    @pick_items = @pick.pick_items
    nums = params[:nums]
    objs = nums.split("$")
    begin
      PickItem.transaction do
        objs.each do |obj|
          obj_arr = obj.split(",")
          id = obj_arr[0]
          count = obj_arr[1]
          pick_item = @pick_items.find(id)
          pick_item.add_count(count)
        end
      end
    rescue
      flash[:warning] = "数据不合法"
      redirect_to project_pick_pick_items_path(@project, @pick)
      return
    end
    redirect_to project_pick_path(@project, @pick)
  end
   

   
  def show
    @projects = current_user.projects
    @project = @projects.find(params[:project_id])
    @picks = @project.picks
    @pick = @picks.find(params[:pick_id])
    @pick_items = @pick.pick_items
    @pick_item = @pick_items.find(params[:id])
  end
   

   
  def new
    @projects = current_user.projects
    @project = @projects.find(params[:project_id])
    @picks = @project.picks
    @pick = @picks.find(params[:pick_id])
    @pick_item = PickItem.new
  end
   

   
  def create
    @projects = current_user.projects
    @project = @projects.find(params[:project_id])
    @picks = @project.picks
    @pick = @picks.find(params[:pick_id])
    @pick_item = PickItem.new(pick_item_params)
    @pick_item.pick = @pick 
    if @pick_item.save
      redirect_to project_pick_pick_items_path(@project, @pick)
    else
      render :new
    end
  end
   

   
  def edit
    @projects = current_user.projects
    @project = @projects.find(params[:project_id])
    @picks = @project.picks
    @pick = @picks.find(params[:pick_id])
    @pick_items = @pick.pick_items
    @pick_item = @pick_items.find(params[:id])
  end
   

   
  def update
    @projects = current_user.projects
    @project = @projects.find(params[:project_id])
    @picks = @project.picks
    @pick = @picks.find(params[:pick_id])
    @pick_items = @pick.pick_items
    @pick_item = @pick_items.find(params[:id])
    if @pick_item.update(pick_item_params)
      redirect_to project_pick_pick_items_path(@project, @pick)
    else
      render :edit
    end
  end
   

   
  def destroy
    @projects = current_user.projects
    @project = @projects.find(params[:project_id])
    @picks = @project.picks
    @pick = @picks.find(params[:pick_id])
    @pick_items = @pick.pick_items
    @pick_item = @pick_items.find(params[:id])
    @pick_item.destroy
    redirect_to project_pick_pick_items_path(@project, @pick)
  end
   

  

  

  private
    def pick_item_params
      params.require(:pick_item).permit( :count)
    end
  
  
  
end

app/views/pick_items/_form.html.haml
.container-fluid
  .row.justify-content-sm-center
    .col-sm-12
      = form_for @pick_item, :builder => WebsiteFormBuilder, :html => {:'data-parsley-validate' => true} do |f|
        - if @pick_item.errors.any?
          #error_explanation.alert.alert-danger.alert-dismissible.fade.show
            %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
              %span{"aria-hidden" => "true"} x 
            %h2= "#{pluralize(@pick_item.errors.count, "error")} prohibited this buyer from being saved:"
            %ul
              - @pick_item.errors.full_messages.each do |msg|
                %li= msg
      
        .form-group.row
          = f.label Setting.pick_items.count, :class => "col-sm-3 col-form-label text-right"
          .col-sm-6
            = f.number_field :count, :class => "form-control rounded-0" , :required => true
          
      
      
      
      
      
        .form-group.row
          .col-3.offset-3
            = f.submit '保存', :class => "button button-action"
        -#
          .col-3.offset-1
            = link_to '返回', pick_items_path, :class => "button button-caution"

app/views/pick_items/edit.html.haml
- provide(:title, t('.title'))

.container-fluid
  .row
    = render "layouts/control_sidebar"
    %main.col-md-9.ml-sm-auto.col-lg-10.p-3{:role => "main"}
      - content_for :card_header do
        %h5
          = fa_icon "wpforms", text: t(controller_name + "." + action_name + '.title')
          = link_to "#{request.url}".sub("edit", ""), :class => "button pull-right button-primary" do
            = fa_icon " chevron-left", text: Setting.systems.btn_back, right: false 

      - content_for :card_body do
        .container-fluid.p-0
          .row
            .col-md-12
              .card-body
                = render 'form'

      = render "layouts/bootstrap/card"

app/views/pick_items/index.html.haml
- provide(:title, t('.title'))


.container-fluid
  .row
    = render "layouts/control_sidebar"
    %main.col-md-9.ml-sm-auto.col-lg-10.p-3{:role => "main"}
      - content_for :card_header do
        %h5
          = fa_icon "list", text: "出料单明细"
          - if @pick.pick_items.size > 0
            %button#pick-item-save{:type => "button", :class => "button pull-right button-small button-caution mr-1"}
              = fa_icon "save", text: "下一步", right: false 
          = link_to edit_project_pick_path(@project, @pick), :class => "button pull-right button-small button-primary mr-1" do
            = fa_icon " chevron-left", text: "上一步", right: false 
          %button{:type => "button", :class => "button pull-right button-small button-royal mr-1", :"data-toggle" =>"modal", :"data-target" => "#stockModal" }
            = fa_icon "plus", text: Setting.systems.btn_new, right: false 
      - content_for :card_body do
        .container-fluid
          .row
            .col-md-12
              %table.text-center.table-striped.table-sm{:'data-toggle' => "table", :"data-pagination"=>"true", :'data-id-table'=>"advancedTable"}
                %thead
                  %tr
                    %th{:scope => "col"} #
                  
                    %th.w-10{:scope => "col"}
                      = Setting.ctg_mtrls.idno
                    %th.w-50{:scope => "col"}
                      = Setting.ctg_mtrls.name
                    %th.w-10{:scope => "col"}
                      = Setting.ctg_mtrls.model_no
                    %th.w-10{:scope => "col"}
                      = Setting.stocks.unit_price
                    %th.w-10{:scope => "col"}
                      剩余
                    %th{:scope => "col"}
                      = Setting.pick_items.count
                    %th{:scope => "col"}
                      设置
                %tbody
                  - @pick_items.each_with_index do |pick_item, index|
                    %tr
                      %td{:scope => "row"}
                        %span.pick-item-index{:hidden => "true"}
                          = pick_item.id
                        = index+1
                    
                      %td
                        = pick_item.stock.ctg_mtrl.idno
                      %td
                        = pick_item.stock.ctg_mtrl.name
                      %td
                        = pick_item.stock.ctg_mtrl.model_no
                      %td
                        = pick_item.stock.unit_price
                      %td
                        %span.stock-count
                          = pick_item.stock.count
                      %td
                        = number_field_tag "pick_count", pick_item.count, :class => "form-control pick-count"
                      %td
                        .container-fluid
                          .row.justify-content-center
                            = link_to "删除",  project_pick_pick_item_path(@project, @pick, pick_item), :method => :delete, :data => {:confirm => "确定删除吗?"}, :class => "button button-caution button-small" 
      = render "layouts/bootstrap/card"

#stockModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "stockModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog.modal-dialog-centered.modal-xl
    .modal-content
      .modal-header
        %button{:type => "button", :class =>"close", :"data-dismiss" => "modal", :"aria-label" => "Close"}
          %span{:"aria-hidden" => "true"}
            &times;
      .modal-body
        -#
          %table.text-center.table-sm{:'data-search' => "true", :"data-click-to-select" => "true", :"data-checkbox-header" => "false", :'data-toggle' => "table", :"data-pagination"=>"true", :'data-id-table'=>"advancedTable"}
        %table#stock-table.text-center.table-sm{:'data-search' => "true", :"data-click-to-select" => "true", :"data-checkbox-header" => "true", :'data-toggle' => "table", :"data-height" =>"460", :'data-url' => "/projects/#{@project.id}/picks/#{@pick.id}/pick_items/current_stock" }
          
          %thead
            %tr
              %th{:"data-field" => "index", "data-checkbox" => "true" }
              %th{:"data-field" => "idno"}
                = Setting.ctg_mtrls.idno
              %th{:"data-field" => "name"}
                = Setting.ctg_mtrls.name
              %th{:"data-field" => "model_no"}
                = Setting.ctg_mtrls.model_no
              %th{:"data-field" => "pet_name"}
                = Setting.ctg_mtrls.pet_name
              %th{:"data-field" => "unit_price"}
                = Setting.stocks.unit_price
              %th{:"data-field" => "count"}
                = Setting.stocks.count
      .modal-footer
        %button#stock-table-btn.button.button-primary{:type => "button"}
          确定

app/views/pick_items/show.html.haml
- provide(:title, t('.title'))

.container-fluid
  .row
    = render "layouts/control_sidebar"
    %main.col-md-9.ml-sm-auto.col-lg-10.p-3{:role => "main"}
      - content_for :card_header do
        %h5
          = fa_icon "newspaper-o", text: t(controller_name + "." + action_name + '.title')
          = link_to "/#{controller_name}", :class => "button pull-right button-primary" do
            = fa_icon " chevron-left", text: Setting.systems.btn_back, right: false 
      - content_for :card_body do
        .container-fluid
          .row
            .col-md-8.offset-2
              .card-body
                .container-fluid
                  .row
                  
                    .col-md-6.mb-3.mr-3
                      = Setting.pick_items.count
                      = @pick_item.count
                  
                  .row
                  
                  .row
                  
                  .row
                  
                  
                  .row
                  
      = render "layouts/bootstrap/card"